"""phases_2_through_5_schema

Revision ID: a636765bb0f0
Revises: 06fd0c29fcb8
Create Date: 2026-03-14 10:34:11.974199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a636765bb0f0'
down_revision: Union[str, None] = '06fd0c29fcb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('time_offset_ms', sa.Integer(), nullable=False),
    sa.Column('hash_hex', sa.String(length=16), nullable=False),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['videos.content_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_fingerprints_content_id'), 'audio_fingerprints', ['content_id'], unique=False)
    op.add_column('videos', sa.Column('author_public_key', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('active_signals_json', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('rs_n', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('pilot_hash_48', sa.BigInteger(), nullable=True))
    op.add_column('videos', sa.Column('manifest_signature', sa.LargeBinary(), nullable=True))
    op.add_column('videos', sa.Column('status', sa.String(length=20), server_default='VALID', nullable=False))
    op.alter_column('videos', 'content_hash_sha256',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('videos', 'storage_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'storage_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('videos', 'content_hash_sha256',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('videos', 'status')
    op.drop_column('videos', 'manifest_signature')
    op.drop_column('videos', 'pilot_hash_48')
    op.drop_column('videos', 'rs_n')
    op.drop_column('videos', 'active_signals_json')
    op.drop_column('videos', 'author_public_key')
    op.drop_index(op.f('ix_audio_fingerprints_content_id'), table_name='audio_fingerprints')
    op.drop_table('audio_fingerprints')
    # ### end Alembic commands ###
