"""
Integration tests for sign_audio → verify_audio end-to-end pipeline.

Uses synthetic audio generated by ffmpeg with anoisesrc (not sine — spectral
concentration in sine kills DWT detail bands). Marked @pytest.mark.slow.

Run:
    pytest tests/integration/test_sign_verify_audio_only.py -v
"""
from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

import pytest

from kernel_backend.core.domain.identity import Certificate
from kernel_backend.core.domain.verification import RedReason, VerificationResult, Verdict
from kernel_backend.core.services.crypto_service import generate_keypair
from kernel_backend.core.services.signing_service import sign_audio
from kernel_backend.core.services.verification_service import VerificationService
from kernel_backend.infrastructure.media.media_service import MediaService
from tests.helpers.fakes import FakeRegistry, FakeStorage

PEPPER = b"integration-test-pepper-padded!!"


def _make_cert(public_key_pem: str) -> Certificate:
    return Certificate(
        author_id="integration-author",
        name="Integration Test Author",
        institution="Test Org",
        public_key_pem=public_key_pem,
        created_at="2026-01-01T00:00:00+00:00",
    )


@pytest.fixture(scope="module")
def synthetic_audio_120s(tmp_path_factory) -> Path:
    """120-second broadband noise audio — 60 segments × 2s; well above ≥17 RS minimum."""
    tmp = tmp_path_factory.mktemp("integ_audio")
    out = tmp / "audio_120s.wav"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anoisesrc=duration=120:sample_rate=44100",
            "-ac", "1",
            str(out),
        ],
        check=True,
        capture_output=True,
    )
    return out


@pytest.fixture(scope="module")
def synthetic_audio_unsigned(tmp_path_factory) -> Path:
    """30-second audio file that is never signed — used for CANDIDATE_NOT_FOUND."""
    tmp = tmp_path_factory.mktemp("integ_audio_unsigned")
    out = tmp / "unsigned.wav"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anoisesrc=duration=30:sample_rate=44100",
            "-ac", "1",
            str(out),
        ],
        check=True,
        capture_output=True,
    )
    return out


@pytest.mark.integration
@pytest.mark.slow
async def test_audio_sign_verify_roundtrip_clean(synthetic_audio_120s: Path) -> None:
    """
    [BLOCKING] sign_audio → verify_audio clean roundtrip on a 120s noise file.
    Assert verdict=VERIFIED, wid_match=True, signature_valid=True.
    """
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)
    storage = FakeStorage()
    registry = FakeRegistry()
    media = MediaService()

    sign_result = await sign_audio(
        media_path=synthetic_audio_120s,
        certificate=cert,
        private_key_pem=private_pem,
        storage=storage,
        registry=registry,
        pepper=PEPPER,
        media=media,
    )

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        signed_path = Path(tmp.name)
    try:
        signed_bytes = await storage.get(sign_result.signed_media_key)
        signed_path.write_bytes(signed_bytes)

        service = VerificationService()
        result: VerificationResult = await service.verify_audio(
            media_path=signed_path,
            media=media,
            storage=storage,
            registry=registry,
            pepper=PEPPER,
        )
    finally:
        signed_path.unlink(missing_ok=True)

    assert result.verdict == Verdict.VERIFIED, (
        f"Expected VERIFIED but got {result.verdict} (reason={result.red_reason})"
    )
    assert result.wid_match is True
    assert result.signature_valid is True


@pytest.mark.integration
async def test_audio_unsigned_returns_red_candidate_not_found(
    synthetic_audio_unsigned: Path,
) -> None:
    """
    [BLOCKING — security] An unsigned audio file must return RED(CANDIDATE_NOT_FOUND).
    The fingerprint lookup finds no matching candidate in the empty registry.
    """
    media = MediaService()
    registry = FakeRegistry()  # empty — no signed content
    storage = FakeStorage()

    service = VerificationService()
    result: VerificationResult = await service.verify_audio(
        media_path=synthetic_audio_unsigned,
        media=media,
        storage=storage,
        registry=registry,
        pepper=PEPPER,
    )

    assert result.verdict == Verdict.RED
    assert result.red_reason == RedReason.CANDIDATE_NOT_FOUND


@pytest.mark.integration
@pytest.mark.slow
async def test_audio_sign_verify_aac_recompression(
    synthetic_audio_120s: Path, tmp_path: Path
) -> None:
    """
    [BLOCKING] sign_audio → AAC 128k recompression → verify_audio.
    With target_snr_db=-14.0 dB (sign_audio default) and 256k signing bitrate,
    AAC 128k recompression should leave WID intact.
    """
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)
    storage = FakeStorage()
    registry = FakeRegistry()
    media = MediaService()

    sign_result = await sign_audio(
        media_path=synthetic_audio_120s,
        certificate=cert,
        private_key_pem=private_pem,
        storage=storage,
        registry=registry,
        pepper=PEPPER,
        media=media,
    )

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        signed_path = Path(tmp.name)
    recompressed_path = tmp_path / "recompressed_128k.m4a"
    try:
        signed_bytes = await storage.get(sign_result.signed_media_key)
        signed_path.write_bytes(signed_bytes)
        subprocess.run(
            [
                "ffmpeg", "-y",
                "-i", str(signed_path),
                "-c:a", "aac", "-b:a", "128k", "-ar", "44100",
                str(recompressed_path),
            ],
            check=True,
            capture_output=True,
        )
    finally:
        signed_path.unlink(missing_ok=True)

    service = VerificationService()
    result: VerificationResult = await service.verify_audio(
        media_path=recompressed_path,
        media=media,
        storage=storage,
        registry=registry,
        pepper=PEPPER,
    )

    assert result.verdict == Verdict.VERIFIED, (
        f"AAC 128k: expected VERIFIED but got {result.verdict} "
        f"(reason={result.red_reason})"
    )
