"""
Unit tests for Phase 5 MediaPort extensions:
  - seek_frame()
  - iter_video_segments(frame_stride)

Uses a synthetic video generated by ffmpeg — no polygon clips required.
"""
from __future__ import annotations

import subprocess
import tracemalloc
from pathlib import Path

import numpy as np
import pytest

from kernel_backend.infrastructure.media.media_service import MediaService


@pytest.fixture(scope="module")
def synthetic_video(tmp_path_factory) -> Path:
    """60-second synthetic video at 320×240, 25fps. ~12 segments at 5s/seg."""
    tmp = tmp_path_factory.mktemp("media_ext")
    out = tmp / "test.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "testsrc=duration=60:size=320x240:rate=25",
            "-vcodec", "libx264", "-crf", "28", "-preset", "ultrafast", "-an",
            str(out),
        ],
        check=True,
        capture_output=True,
    )
    return out


@pytest.fixture(scope="module")
def synthetic_video_640(tmp_path_factory) -> Path:
    """30-second synthetic video at 640×480, 25fps for memory footprint test."""
    tmp = tmp_path_factory.mktemp("media_ext_640")
    out = tmp / "test_640.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "testsrc=duration=30:size=640x480:rate=25",
            "-vcodec", "libx264", "-crf", "28", "-preset", "ultrafast", "-an",
            str(out),
        ],
        check=True,
        capture_output=True,
    )
    return out


def test_seek_frame_returns_correct_shape(synthetic_video: Path) -> None:
    """seek_frame returns a valid BGR uint8 frame at the requested timestamp."""
    media = MediaService()
    frame = media.seek_frame(synthetic_video, time_s=1.0)

    assert frame.dtype == np.uint8
    assert frame.ndim == 3
    h, w, c = frame.shape
    assert c == 3
    assert h == 240
    assert w == 320


def test_seek_frame_raises_on_out_of_bounds(synthetic_video: Path) -> None:
    """seek_frame raises ValueError when requesting a timestamp beyond duration."""
    media = MediaService()
    with pytest.raises(ValueError):
        media.seek_frame(synthetic_video, time_s=9999.0)


def test_iter_segments_stride1_yields_all_frames(synthetic_video: Path) -> None:
    """With frame_stride=1, every frame in the segment is returned."""
    media = MediaService()
    segment_duration_s = 5.0
    fps = 25.0
    expected_frames_per_segment = int(segment_duration_s * fps)  # 125

    first_seg = next(media.iter_video_segments(synthetic_video, segment_duration_s=5.0, frame_stride=1))
    _, frames, reported_fps = first_seg

    assert reported_fps == pytest.approx(fps, abs=1.0)
    assert len(frames) == expected_frames_per_segment


def test_iter_segments_stride3_yields_one_third_frames(synthetic_video: Path) -> None:
    """With frame_stride=3, approximately 1/3 of frames per segment are returned."""
    media = MediaService()
    segment_duration_s = 5.0
    fps = 25.0
    total_frames = int(segment_duration_s * fps)  # 125
    # stride=3: frames at indices 0,3,6,...,123 → ceil(125/3) = 42
    expected = len(range(0, total_frames, 3))

    _, frames, _ = next(media.iter_video_segments(synthetic_video, segment_duration_s=5.0, frame_stride=3))

    assert len(frames) == expected


def test_iter_segments_stride3_same_segment_count_as_stride1(synthetic_video: Path) -> None:
    """frame_stride affects frames per segment, NOT the number of segments yielded."""
    media = MediaService()

    count_stride1 = sum(
        1 for _ in media.iter_video_segments(synthetic_video, segment_duration_s=5.0, frame_stride=1)
    )
    count_stride3 = sum(
        1 for _ in media.iter_video_segments(synthetic_video, segment_duration_s=5.0, frame_stride=3)
    )

    assert count_stride1 == count_stride3
    assert count_stride1 > 0


def test_memory_footprint_stride3_vs_stride1(synthetic_video_640: Path) -> None:
    """
    Peak memory with stride=3 must be less than half that of stride=1
    for the same video.

    Measures only the first segment to keep the test fast.
    """
    media = MediaService()

    def _measure_peak(stride: int) -> int:
        tracemalloc.start()
        gen = media.iter_video_segments(synthetic_video_640, segment_duration_s=5.0, frame_stride=stride)
        _, frames, _ = next(gen)
        # Hold frames in scope so GC does not reclaim before measurement
        _ = [f.nbytes for f in frames]
        _, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        return peak

    peak_stride1 = _measure_peak(1)
    peak_stride3 = _measure_peak(3)

    assert peak_stride3 < peak_stride1 / 2, (
        f"Expected stride=3 peak ({peak_stride3 / 1024:.0f} KB) < "
        f"stride=1 peak / 2 ({peak_stride1 / 1024 / 2:.0f} KB)"
    )
