"""
Smoke tests for sign_av() — AV signing pipeline.

Uses a synthetic AV file generated by ffmpeg (testsrc + sine audio, 120s).
Tests verify the single-manifest / shared-WID design.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from kernel_backend.core.domain.identity import Certificate
from kernel_backend.core.domain.watermark import SegmentFingerprint, VideoEntry
from kernel_backend.core.ports.registry import RegistryPort
from kernel_backend.core.ports.storage import StoragePort
from kernel_backend.core.services.crypto_service import derive_wid, generate_keypair
from kernel_backend.core.services.signing_service import sign_av
from kernel_backend.infrastructure.media.media_service import MediaService

PEPPER = b"test-pepper-bytes-padded-to-32b!"


@pytest.fixture(scope="module")
def synthetic_av(tmp_path_factory) -> Path:
    """120-second AV file (testsrc video + sine audio). ≥17 segments for both tracks."""
    tmp = tmp_path_factory.mktemp("av")
    out = tmp / "test_av.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "testsrc=duration=120:size=320x240:rate=25",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=120",
            "-c:v", "libx264", "-crf", "28", "-preset", "ultrafast",
            "-c:a", "aac", "-ar", "44100",
            str(out),
        ],
        check=True,
        capture_output=True,
    )
    return out


@pytest.fixture(scope="module")
def video_only(tmp_path_factory) -> Path:
    """30-second video without audio track."""
    tmp = tmp_path_factory.mktemp("av_vonly")
    out = tmp / "video_only.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "testsrc=duration=30:size=320x240:rate=25",
            "-vcodec", "libx264", "-crf", "28", "-preset", "ultrafast", "-an",
            str(out),
        ],
        check=True,
        capture_output=True,
    )
    return out


@pytest.fixture(scope="module")
def audio_only(tmp_path_factory) -> Path:
    """30-second audio-only AAC file."""
    tmp = tmp_path_factory.mktemp("av_aonly")
    out = tmp / "audio_only.aac"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "sine=frequency=440:duration=30",
            "-c:a", "aac", "-ar", "44100",
            str(out),
        ],
        check=True,
        capture_output=True,
    )
    return out


class FakeStorage(StoragePort):
    def __init__(self) -> None:
        self._store: dict[str, bytes] = {}

    async def put(self, key: str, data: bytes, content_type: str) -> None:
        self._store[key] = data

    async def get(self, key: str) -> bytes:
        return self._store[key]

    async def delete(self, key: str) -> None:
        self._store.pop(key, None)

    async def presigned_upload_url(self, key: str, expires_in: int) -> str:
        return f"fake://{key}"

    async def presigned_download_url(self, key: str, expires_in: int) -> str:
        return f"fake://{key}"


class FakeRegistry(RegistryPort):
    def __init__(self) -> None:
        self._videos: dict[str, VideoEntry] = {}
        self._segments: list[tuple[str, list[SegmentFingerprint], bool]] = []

    async def save_video(self, entry: VideoEntry) -> None:
        self._videos[entry.content_id] = entry

    async def get_by_content_id(self, content_id: str) -> VideoEntry | None:
        return self._videos.get(content_id)

    async def get_valid_candidates(self) -> list[VideoEntry]:
        return [e for e in self._videos.values() if e.status == "VALID"]

    async def save_segments(
        self, content_id: str, segments: list[SegmentFingerprint], is_original: bool
    ) -> None:
        self._segments.append((content_id, list(segments), is_original))

    async def match_fingerprints(
        self, hashes: list[str], max_hamming: int = 10
    ) -> list[VideoEntry]:
        return []


def _make_cert(public_key_pem: str) -> Certificate:
    return Certificate(
        author_id="test-author-id",
        name="Test Author",
        institution="Test Org",
        public_key_pem=public_key_pem,
        created_at="2026-01-01T00:00:00+00:00",
    )


async def test_sign_av_returns_valid_result(synthetic_av: Path) -> None:
    """sign_av returns valid content_id, 16-byte WID, 64-byte sig, 6 active signals."""
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)
    registry = FakeRegistry()

    result = await sign_av(
        media_path=synthetic_av,
        certificate=cert,
        private_key_pem=private_pem,
        storage=FakeStorage(),
        registry=registry,
        pepper=PEPPER,
        media=MediaService(),
    )

    assert len(result.wid.data) == 16
    assert len(result.signature) == 64
    parts = result.content_id.split("-")
    assert len(parts) == 5  # valid UUID v4

    assert set(result.active_signals) == {
        "audio_pilot", "audio_wid", "audio_fingerprint",
        "video_pilot", "video_wid", "video_fingerprint",
    }

    # Registry should have one VideoEntry with all 6 signals
    entry = registry._videos[result.content_id]
    assert set(entry.active_signals) == set(result.active_signals)


async def test_sign_av_raises_on_video_only(video_only: Path) -> None:
    """sign_av raises ValueError when the container has no audio track."""
    private_pem, public_pem = generate_keypair()
    with pytest.raises(ValueError, match="both audio and video tracks"):
        await sign_av(
            media_path=video_only,
            certificate=_make_cert(public_pem),
            private_key_pem=private_pem,
            storage=FakeStorage(),
            registry=FakeRegistry(),
            pepper=PEPPER,
            media=MediaService(),
        )


async def test_sign_av_raises_on_audio_only(audio_only: Path) -> None:
    """sign_av raises ValueError when the container has no video track."""
    private_pem, public_pem = generate_keypair()
    with pytest.raises(ValueError, match="both audio and video tracks"):
        await sign_av(
            media_path=audio_only,
            certificate=_make_cert(public_pem),
            private_key_pem=private_pem,
            storage=FakeStorage(),
            registry=FakeRegistry(),
            pepper=PEPPER,
            media=MediaService(),
        )


async def test_sign_av_uses_smaller_rs_n(synthetic_av: Path) -> None:
    """sign_av uses min(rs_n_audio, rs_n_video) as the shared codeword length."""
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)
    registry = FakeRegistry()

    result = await sign_av(
        media_path=synthetic_av,
        certificate=cert,
        private_key_pem=private_pem,
        storage=FakeStorage(),
        registry=registry,
        pepper=PEPPER,
        media=MediaService(),
    )

    # 120s video → video: 120/5 = 24 segments, audio: 120/2 = 60 segments
    # rs_n_video=24 < rs_n_audio=60 → rs_n=24
    entry = registry._videos[result.content_id]
    assert entry.rs_n == result.rs_n
    assert result.rs_n <= 24  # video segments cap it


async def test_shared_wid_is_identical_for_both_channels(synthetic_av: Path) -> None:
    """
    The same WID is embedded in both audio and video tracks.
    Verified by checking that re-deriving WID from the stored signature
    matches the returned WID — one signature → one WID for both channels.
    """
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)
    registry = FakeRegistry()

    result = await sign_av(
        media_path=synthetic_av,
        certificate=cert,
        private_key_pem=private_pem,
        storage=FakeStorage(),
        registry=registry,
        pepper=PEPPER,
        media=MediaService(),
    )

    # Re-derive WID from the stored signature
    entry = registry._videos[result.content_id]
    rederived_wid = derive_wid(entry.manifest_signature, result.content_id)

    # Single WID — same object for both channels
    assert result.wid.data == rederived_wid.data
    # There should be only ONE VideoEntry (not two separate audio/video entries)
    assert len(registry._videos) == 1
